language: android
sudo: false
android:
  components:
  - build-tools-24.0.2
  - android-24
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-19
  - sys-img-armeabi-v7a-android-19
  - sys-img-x86-android-17
script:
- "./gradlew assembleRelease"
before_install:
- openssl aes-256-cbc -K $encrypted_905d4882b60e_key -iv $encrypted_905d4882b60e_iv
  -in tci.jks.enc -out tci.jks -d
